added and updated escaping
cloudsponge/better-sharing-wp pull request #46
Opened 2020-12-22 00:35 UTC by bszyk

all $_POST and $_GETs are sanitized already
also added rel="noopener noreferrer" to two instances of target="_blank"

2020-12-22 01:10 UTC, circuitfive commented
@bszyk the message from the review team specifically mentions the following instances of  `$_POST` needing sanitizing:

https://github.com/cloudsponge/better-sharing-wp/blob/374543b50799351ed44f0fd536c784bd4cec6761/includes/AdminScreens/AddOns.php#L73

https://github.com/cloudsponge/better-sharing-wp/blob/374543b50799351ed44f0fd536c784bd4cec6761/includes/AdminScreens/GeneralSettings.php#L53

2020-12-22 01:17 UTC, royboy789 requested changes
@circuitfive is correct, will need those 2 lines addressed.

All these additions are great otherwise.

2021-01-01 17:51 UTC, royboy789 approved these changes

2021-01-01 17:52 UTC, royboy789 commented
@circuitfive sorry didn't see the notification come in. All looks good, ready to merge and update sent to org.

2021-01-04 02:26 UTC, merged